name: Automatisation récupération des données RTE

on:
  push: 
  schedule:  
    - cron: "10 13 * * *"  # Exécution quotidienne à 13h10 UTC (14h10 heure française)

jobs:
  fetch-data:
    runs-on: ubuntu-22.04  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: python script.py